# -*- coding: utf-8 -*-
"""ejercicioTresPilas.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11JjBgnGcze6qLOmSgE8EhhTS_E8b1EQr
"""

# Clase Pila
class Pila:
    def __init__(self):
        self.items = []

    def push(self, dato):
        self.items.append(dato)

    def pop(self):
        return self.items.pop() if not self.is_empty() else None

    def is_empty(self):
        return len(self.items) == 0


# Clase Editor de Texto con función Deshacer
class EditorTexto:
    def __init__(self):
        self.texto = ""
        self.historial = Pila()

    def escribir(self, nuevo_texto):
        # Guardar el estado actual antes de modificarlo
        self.historial.push(self.texto)
        self.texto += nuevo_texto

    def deshacer(self):
        if not self.historial.is_empty():
            self.texto = self.historial.pop()
        else:
            print("No hay más acciones para deshacer.")

    def mostrar(self):
        print(f"Texto actual: '{self.texto}'")


# ----------- PROGRAMA PRINCIPAL -----------
editor = EditorTexto()

while True:
    print("\nOpciones:")
    print("1. Escribir texto")
    print("2. Deshacer última acción")
    print("3. Mostrar texto")
    print("4. Salir")

    opcion = input("Elige una opción: ")

    if opcion == "1":
        mensaje = input("Escribe el texto que deseas agregar: ")
        editor.escribir(mensaje)
    elif opcion == "2":
        editor.deshacer()
    elif opcion == "3":
        editor.mostrar()
    elif opcion == "4":
        print("Saliendo del editor...")
        break
    else:
        print("Opción inválida, intenta de nuevo.")