# -*- coding: utf-8 -*-
"""ejercicioUnoPilas.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbAITko0MhlaaoFMwlsBImnHbr1mK0El
"""

#1. Paréntesis balanceados
#Diseña un programa que use una pila para comprobar si una expresión matemática
#tiene los paréntesis correctamente balanceados.


class Pila:
    def __init__(self):
        self.items = []

    def push(self, dato):
        self.items.append(dato)

    def pop(self):
        return self.items.pop() if not self.is_empty() else None

    def is_empty(self):
        return len(self.items) == 0

def parentesis_balanceados(expresion):
    pila = Pila()
    for caracter in expresion:
        if caracter == '(':
            pila.push(caracter)
        elif caracter == ')':
            if pila.is_empty():
                return False
            pila.pop()
    return pila.is_empty()

exp1 = "(2+3)*(5/(7-2))"
exp2 = "((2+3)*5/(7-2)"
exp3 = "((2+3)*5)/(7-2))"

for exp in [exp1, exp2, exp3]:
    if parentesis_balanceados(exp):
        print(f"{exp} -> Balanceado")
    else:
        print(f"{exp} -> No balanceado")